### ISSUE TITLE
`godeps` doesn't like nested Go modules

### ISSUE THREAD

**Issue by robbrit** [sagikazarmark/please-go-modules#30]
In our monorepo we had many Go apps that have their own subdirectories with go.mod files, and we're slowly switching to Please.

`go env GOMOD` gives back `/dev/null` if the go.mod file is not present in the top-level directory (). This results in a panic:

```
> plz godeps
panic: open /dev/null.sum: no such file or directory

goroutine 1 [running]:
main.main()
	cmd/godeps/main.go:80 +0x1f46
```

The fix is to copy the go.mod and go.sum files to the top-level when we want to add packages, and then update any `replace` fields in go.mod. Not the end of the world as a workaround, but it'd be awesome to be able to point to a directory and run within the context of that directory rather than assuming the top level.

**Comment by sagikazarmark** [comment]
The examples in the repo are actually go submodules:

https://github.com/sagikazarmark/please-go-modules/tree/master/example

Would that work for you?

I actually use the tool in a project with submodules: https://github.com/banzaicloud/pipeline

Which version of godeps do you use?

**Comment by robbrit** [comment]
We're not using godeps at all, we're just using vanilla Go modules. The repository is a monorepo with several Go projects in it that are currently all independent, but they share proto files that get built using some hand-rolled scripts. There's no go.mod file at the top-level.

If I try creating an empty go.mod and go.sum files at the top level, it panics again:
```
> plz godeps
panic: exit status 1

goroutine 1 [running]:
main.main()
	cmd/godeps/main.go:66 +0x1f54
```

**Comment by sagikazarmark** [comment]
> We're not using godeps at all, we're just using vanilla Go modules. 

I guess you mean the godeps dep manager tool. Which version of this repo do you use?

> The repository is a monorepo with several Go projects in it 

That's exactly how the examples work like: https://github.com/sagikazarmark/please-go-modules/tree/master/example

Take a look at the readme.

> If I try creating an empty go.mod and go.sum files at the top level, it panics again:

Under the hood, the tool runs `go list`. If it fails, godeps will fail too. I can see two potential solutions for your use case:

- Create a go.mod file at the top level and import all submodules as well (with the appropriate replaces pointing to the local folders). That should create a top level `third_party` directory for you.
- Run the godeps tool in each module like in the examples I mentioned above

**Comment by robbrit** [comment]
Got it, I'll give that a shot.

Can I make a feature request? Instead of panicking when these subcommands fail, can we print out a useful error message when things go wrong? For example "missing go.mod" or something like that when `go env` gives back `/dev/null`.

**Comment by sagikazarmark** [comment]
Yeah, that's definitely desirable. I'll improve the error handling.

**Comment by robbrit** [comment]
Awesome, `go list` found the problem. I was missing a `go.mod` file in one of the subdirectories; we had been using Bazel for this one from the beginning and so never made the go.mod file.
